---
- name: Install HAProxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Deploy HAProxy config from template
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: restart haproxy

- name: Ensure HAProxy is running
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

